### ISSUE TITLE
Tool tip/ Description of fields

### ISSUE THREAD

**Issue by YaraKtva** [WomenPlusPlus/deploy-impact-23-kpi-2#10]
As a new user i would like to see the step by step instruction (/ description of fields) related to work of new app.
I need to understand How/Where/When the update should be done from Circle(team)/Individual.

Needs to have description for the fields of KPI ( Input menu)

**Comment by YaraKtva** [comment]
@dianaarchi  to add description   of fields.

**Comment by YaraKtva** [comment]
@dianaarchi @mmarianah @MichaelMa-mkk pls make sure the right assignee in place alongside the ticket process.Thank you !

**Comment by dianaarchi** [comment]
Done

**Comment by dianaarchi** [comment]
Descriptions done
