### ISSUE TITLE
As DS, I want to update and improve predictive analytics with new data provided by PO.

### ISSUE THREAD

**Issue by GiadaFallo** [WomenPlusPlus/deploy-impact-23-kpi-2#30]

**Comment by dianaarchi** [comment]
There wont be data coming from PO. Will create a toy dataset and produce the predictive analytics from there. The most important in the project is what the dashboard can do, not the truthfulness of the data used at this point.

**Comment by dianaarchi** [comment]
Predictive analytics are oos

**Comment by dianaarchi** [comment]
OOS
