### ISSUE TITLE
When saving KPI with no inserted value --> should not be saved--> have an error  message.

### ISSUE THREAD

**Issue by GiadaFallo** [WomenPlusPlus/deploy-impact-23-kpi-2#79]
When a user ties to save a Value field without an inserted value --> the field should not be saved. (DEV)

User should see a general error message (UX/UI) if record cant be saved to clear the visualisation and understanding for user .

**Comment by YaraKtva** [comment]
DEV + UIX/UI

**Comment by elilisaehr** [comment]
I've added this screen for the dev team with some error message: https://www.figma.com/file/4C32qXR71cVyO6ykukVgMT/Pro-Juventute-Design-System?type=design&node-id=1101%3A20101&mode=design&t=62pay61ry6dYAcOj-1
