### ISSUE TITLE
TOOLTIP: Indicate that VALUES have to be in “%”  and between 0-100% .Add sign %

### ISSUE THREAD

**Issue by GiadaFallo** [WomenPlusPlus/deploy-impact-23-kpi-2#80]

**Comment by elilisaehr** [comment]
https://www.figma.com/file/4C32qXR71cVyO6ykukVgMT/Pro-Juventute-Design-System?type=design&node-id=527%3A11171&mode=design&t=62pay61ry6dYAcOj-1
